---
from: squash@spin42.me
domain: spin42.me
strategy: smtp
smtp_settings:
  address: mail.spin42.com
  port: '587'
  domain: spin42.me
  user_name: squash@spin42.me
  password: qslkd,l
  authentication: plain
  enable_starttls_auto: true
